Repository site-bucketlist-capstone/buckethero, pull requests merged in 2022-07, with the labels that each got.

#80 Gallery Page functionality with styling and dropdown
  bucket-hero-ui/src/components/Gallery.jsx
  bucket-hero-ui/src/components/GalleryListItems.jsx
  bucket-hero-ui/src/components/GalleryNewItem.jsx
  bucket-hero-ui/src/contexts/gallery.jsx
Labels: enhancement

#81 Edit list page completed
  bucket-hero-ui/src/components/EditList.jsx
  bucket-hero-ui/src/components/EditListItem.jsx
  bucket-hero-ui/src/services/apiClient.js
Labels: Front End

#84 Styling updates for responsive design
  .DS_Store
  bucket-hero-ui/src/components/ComingUp.jsx
  bucket-hero-ui/src/components/Completed.jsx
  bucket-hero-ui/src/components/Dashboard.jsx
  bucket-hero-ui/src/components/EditItem.jsx
  bucket-hero-ui/src/components/EditList.jsx
  bucket-hero-ui/src/components/EditListItem.jsx
  bucket-hero-ui/src/components/Gallery.jsx
  bucket-hero-ui/src/components/GalleryListItems.jsx
  bucket-hero-ui/src/components/GalleryNewItem.jsx
  bucket-hero-ui/src/components/Hero.jsx
  bucket-hero-ui/src/components/ListCol.jsx
  bucket-hero-ui/src/components/ListItemComp.jsx
  bucket-hero-ui/src/components/ListItems.jsx
  bucket-hero-ui/src/components/NavBar.jsx
  bucket-hero-ui/src/components/NewItem.jsx
  bucket-hero-ui/src/components/NewList.jsx
  bucket-hero-ui/src/components/Profile.jsx
Labels: enhancement

#85 footer created
  bucket-hero-ui/src/App.jsx
  bucket-hero-ui/src/components/Footer.jsx
  bucket-hero-ui/src/components/NavBar.jsx
Labels: enhancement

#110 Gallery Item stretch feature in progress
  buckethero-api/buckethero-schema.sql
  buckethero-api/models/gallery.js
  buckethero-api/models/items.js
  buckethero-api/routes/global.js
Labels: STRETCH, Back End

#114 stretch gallery feature in rpogress
  bucket-hero-ui/src/components/EditList.jsx
  bucket-hero-ui/src/components/Gallery.jsx
Labels: STRETCH, Back End

#115 Updated gallery backend
  .DS_Store
  buckethero-api/.DS_Store
  buckethero-api/buckethero-schema.sql
  buckethero-api/models/gallery.js
  buckethero-api/models/items.js
  buckethero-api/routes/global.js
Labels: STRETCH, Back End

#118 Cleaned up styling, spacing, and responsiveness
  bucket-hero-ui/index.html
  bucket-hero-ui/src/App.jsx
  bucket-hero-ui/src/components/ComingUp.jsx
  bucket-hero-ui/src/components/EditItem.jsx
  bucket-hero-ui/src/components/EditList.jsx
  bucket-hero-ui/src/components/EditListItem.jsx
  bucket-hero-ui/src/components/Footer.jsx
  bucket-hero-ui/src/components/Hero.jsx
  bucket-hero-ui/src/components/ListCol.jsx
  bucket-hero-ui/src/components/ListItemComp.jsx
  bucket-hero-ui/src/components/ListItems.jsx
  bucket-hero-ui/src/components/NavBar.jsx
  bucket-hero-ui/src/components/NewItem.jsx
  bucket-hero-ui/src/components/NewList.jsx
  bucket-hero-ui/src/components/Profile.jsx
Labels: Front End, Cleanup
