Repository site-bucketlist-capstone/buckethero, pull requests merged in 2022-08, with the labels that each got.

#121 cleaning up spacing and wording in UI, including changing Gallery to Inspo, and adding a warning message
  bucket-hero-ui/src/App.jsx
  bucket-hero-ui/src/assets/profile-banner.png
  bucket-hero-ui/src/components/Dashboard.jsx
  bucket-hero-ui/src/components/Footer.jsx
  bucket-hero-ui/src/components/Gallery.jsx
  bucket-hero-ui/src/components/GalleryListItems.jsx
  bucket-hero-ui/src/components/Hero.jsx
  bucket-hero-ui/src/components/ListItemComp.jsx
  bucket-hero-ui/src/components/ListItems.jsx
  bucket-hero-ui/src/components/NavBar.jsx
  bucket-hero-ui/src/components/Profile.jsx
Labels: Front End, Cleanup

#128 Users are able to edit profile
  buckethero-api/models/list.js
  buckethero-api/models/profile.js
  buckethero-api/routes/profile.js
Labels: STRETCH, Back End

#131 added name to gallery list item
  bucket-hero-ui/src/components/GalleryListItems.jsx
  buckethero-api/models/gallery.js
Labels: enhancement

#132 Edit profile backend functionality completed.
  bucket-hero-ui/src/contexts/auth.jsx
  bucket-hero-ui/src/services/apiClient.js
  buckethero-api/models/profile.js
  buckethero-api/routes/profile.js
Labels: STRETCH, Back End

#134 Implement functions in both backend and frontend for public profile feature.
  bucket-hero-ui/src/App.jsx
  bucket-hero-ui/src/components/GalleryListItems.jsx
  bucket-hero-ui/src/services/apiClient.js
  buckethero-api/buckethero-schema.sql
  buckethero-api/buckethero-seed.sql
  buckethero-api/models/gallery.js
  buckethero-api/models/items.js
  buckethero-api/models/user.js
  buckethero-api/routes/global.js
  buckethero-api/routes/profile.js
Labels: Front End, STRETCH, Back End

#135 Fixed apiClient bug
  bucket-hero-ui/src/services/apiClient.js
Labels: bug

#136 Advanced search
  bucket-hero-ui/src/components/Gallery.jsx
Labels: enhancement

#138 Edit profile functionalyity in progress
  bucket-hero-ui/src/App.jsx
  bucket-hero-ui/src/components/PublicProfile.jsx
  bucket-hero-ui/src/services/apiClient.js
  buckethero-api/models/gallery.js
Labels: Front End, STRETCH, Back End

#144 updated models/gallery - fixed bug
  buckethero-api/models/gallery.js
Labels: bug, Back End

#143 Profile edit in progress
  bucket-hero-ui/src/App.jsx
  bucket-hero-ui/src/components/EditItem.jsx
  bucket-hero-ui/src/components/GalleryNewItem.jsx
  bucket-hero-ui/src/components/Profile.jsx
  bucket-hero-ui/src/components/ProfileEditForm.jsx
  bucket-hero-ui/src/contexts/auth.jsx
Labels: Front End, STRETCH

#147 Public profile
  bucket-hero-ui/src/components/Completed.jsx
  bucket-hero-ui/src/components/ListItemComp.jsx
  bucket-hero-ui/src/components/ListItems.jsx
  bucket-hero-ui/src/components/Profile.jsx
  bucket-hero-ui/src/components/PublicProfile.jsx
  bucket-hero-ui/src/services/apiClient.js
  buckethero-api/models/items.js
  buckethero-api/routes/data.js
Labels: bug

#148 Profile edit functionality plus tabs
  bucket-hero-ui/src/components/Profile.jsx
  bucket-hero-ui/src/components/ProfileEditForm.jsx
  bucket-hero-ui/src/contexts/auth.jsx
  bucket-hero-ui/src/services/apiClient.js
Labels: Front End

#151 Public profile feature completed & gallery bug fixed'
  bucket-hero-ui/src/components/Gallery.jsx
  bucket-hero-ui/src/components/PublicProfile.jsx
Labels: bug, Front End, STRETCH, Back End

#152 UI for achievement badges and styling on Gallery
  bucket-hero-ui/src/assets/1.png
  bucket-hero-ui/src/assets/2.png
  bucket-hero-ui/src/assets/3.png
  bucket-hero-ui/src/components/Gallery.jsx
  bucket-hero-ui/src/components/GalleryListItems.jsx
  bucket-hero-ui/src/components/Profile.jsx
Labels: enhancement, Front End, Cleanup

#156 styled update password modal on profile page
  bucket-hero-ui/src/components/Profile.jsx
Labels: Cleanup

#157 Emoji handler
  bucket-hero-ui/src/components/NewList.jsx
Labels: enhancement, Front End

#158 Updated emoji handler
  bucket-hero-ui/src/components/NewList.jsx
Labels: enhancement, Front End

#159 Access Forbidden Page added
  bucket-hero-ui/src/App.jsx
  bucket-hero-ui/src/components/AccessForbidden.jsx
  bucket-hero-ui/src/components/NewList.jsx
Labels: enhancement, Front End

#161 Responsive design and cleaning up styling. Getting rid of console.logs
  bucket-hero-ui/src/App.jsx
  bucket-hero-ui/src/components/AccessForbidden.jsx
  bucket-hero-ui/src/components/ComingUp.jsx
  bucket-hero-ui/src/components/Completed.jsx
  bucket-hero-ui/src/components/EditList.jsx
  bucket-hero-ui/src/components/Gallery.jsx
  bucket-hero-ui/src/components/ListItems.jsx
  bucket-hero-ui/src/components/NavBar.jsx
  bucket-hero-ui/src/components/NewList.jsx
  bucket-hero-ui/src/components/Profile.jsx
  bucket-hero-ui/src/components/PublicProfile.jsx
  bucket-hero-ui/src/contexts/dashboard.jsx
  bucket-hero-ui/src/services/apiClient.js
Labels: Front End, Cleanup

#162 final style changes before wednesday submit
  bucket-hero-ui/src/components/Completed.jsx
  bucket-hero-ui/src/components/Gallery.jsx
  bucket-hero-ui/src/components/GalleryListItems.jsx
  bucket-hero-ui/src/components/Profile.jsx
Labels: Cleanup
